apiVersion: v1
kind: Service
metadata:
  namespace: dash
  labels:
    app: elt-dash
  name: elt-dash
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: elt-dash
  type: LoadBalancer
